In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [36]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [37]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [40]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i +=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [41]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [42]:
df['text']= df['text'].apply(lambda x : x.lower())

In [44]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [45]:
df['text']=df['text'].apply(remove_punc)

In [47]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [48]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [49]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [52]:
pip install nltk

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.9.29-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------- ---------------------------- 0.5/1.8 MB 86.9 kB/s eta 0:00:15
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------- ---------------------- 0.8/1.8 MB 66.7 kB/s eta 0:00:16
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------- ---------------- 1.0/1.8 MB 81.0 kB/s eta 0:00:10
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ----------------------------- ---------- 1.3/1.8 MB 90.8 kB/s eta 0:00:06
   ---------------------------------- ----- 1.6/1.8 MB 100.0 kB/s eta 0:00:03
   ---------------------------------- ----- 1.6/1.8 MB 100.0 kB/s eta 0:00:03
   ---------------------------------- ----- 1.6/1.8 MB 100.0 kB/s eta 0:00:03
   ---------------------------------- ----- 1.6/1.8 MB 100.0 kB/s eta 0:00:03
   ---------------------------------- ----- 1.6/1.8 MB 100.0 kB/s eta 0:00:03
   ---------------------------------------- 1.8/1.8 MB 107.8 kB/s  0:00:16
Downloading regex-2026.9.29-cp312-cp312-win_amd64.whl (280 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, regex, nltk

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [regex]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.10.3 regex-2026.9.29 tqdm-4.70.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script tqdm.exe is installed in 'C:\Users\hp\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script nltk.exe is installed in 'C:\Users\hp\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [53]:
import nltk

In [55]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [60]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [61]:
stop_words =   set(stopwords.words('english'))

In [62]:
def remove(txt):
    words = word_tokenize(txt)
    clean_txt = []
    for i in words:
        if not i in stop_words:
            clean_txt.append(i)

    return ' '.join(clean_txt)

In [63]:
df['text'] = df['text'].apply(remove)

In [64]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'